mailer:
  email: 'phantuananhltt@gmail.com'
  confirm_order_expired: 2
validation:
  name_max: 50
  email_max: 255
  origin_max: 50
  code_max: 10
  phone_min: 10
  min_point: 0
  max_point: 6
  number:
    zero: 0
product:
  min_quantity: 1
quantity_per_page: 8
