mailer:
  email: 'phantuananhltt@gmail.com'
validation:
  name_max: 50
  email_max: 255
  password_min: 6
  origin_max: 50
  code_max: 10
  phone_min: 10
  min_point: 0
  max_point: 6
  number:
    zero: 0
